version: '3.8'
services:
  dance_studio_pg:
    image: postgres:15
    container_name: dance_studio_pg
    environment:
      - POSTGRES_DB=dance_studio_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"

  dance_studio_liquibase-migrations:
    image: liquibase/liquibase:4.18
    container_name: dance_studio_liquibase
    depends_on:
      - dance_studio_pg
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/postgres
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
